services:
  postgres:
    image: postgres:13
    container_name: Postgres
    environment:
      - POSTGRES_PASSWORD=senha
      - TZ=America/Sao_Paulo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:ro
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build: ./
    container_name: API
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DATABASE=Host=postgres;Database=AMVBank;Username=postgres;Password=senha;
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_EXCHANGE=amvtransaction
    ports:
      - "80:80"

volumes:
  pgdata:
  rabbitmq_data:
